version: 2.1
jobs:
  build:
    docker:
      - image: silex/emacs:26.3
      - image: python:3.8.3
    steps:
      - checkout
      - run:
          name: Install cask
          command: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - run:
          name: Install project dependencies 
          command: cask install
      - run:
          name: Run tests
          command: cask exec buttercup -L .
