version: 2.1
jobs:
  build:
    docker:
      - image: silex/emacs:26.3-dev
    steps:
      - checkout
      - run:
          name: Install project dependencies 
          command: cask install
      - run:
          name: Run tests
          command: cask exec buttercup -L .
